--- #YAML:1.0
name:                XML-Parser-Wrapper
version:             0.10
abstract:            Simple object wrapper around XML::Parser
license:             ~
author:              
    - DON OWENS <don@regexguy.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    XML::Parser:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
